/* BMI Calculator */
package MyPackage;
import java.text.DecimalFormat;

/**
 * @author DEEEPAK SINGH
 * Date  2 August 2021
 */
public class BMI_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form BMI_Calculator
     */
    public BMI_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        YourHeight = new javax.swing.JLabel();
        Feet = new javax.swing.JLabel();
        Inches = new javax.swing.JLabel();
        Yourweight = new javax.swing.JLabel();
        WeightText = new javax.swing.JTextField();
        CalculateBMI = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        YourBMI = new javax.swing.JLabel();
        BMI = new javax.swing.JTextField();
        FeetText = new javax.swing.JTextField();
        comment = new javax.swing.JLabel();
        InchesText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMI Calculator");

        jPanel1.setBackground(new java.awt.Color(248, 253, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 204), new java.awt.Color(0, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(197, 190, 239));
        jPanel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N

        YourHeight.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        YourHeight.setForeground(new java.awt.Color(0, 0, 255));
        YourHeight.setText("Your height : ");

        Feet.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Feet.setForeground(new java.awt.Color(0, 0, 255));
        Feet.setText("Feet  ");

        Inches.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Inches.setForeground(new java.awt.Color(0, 0, 255));
        Inches.setText("Inches");

        Yourweight.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Yourweight.setForeground(new java.awt.Color(0, 0, 255));
        Yourweight.setText("Your weight : ");

        WeightText.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        WeightText.setForeground(new java.awt.Color(255, 0, 0));
        WeightText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        CalculateBMI.setBackground(new java.awt.Color(255, 255, 0));
        CalculateBMI.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        CalculateBMI.setForeground(new java.awt.Color(255, 0, 0));
        CalculateBMI.setText("Calculate your BMI");
        CalculateBMI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(51, 51, 255)));
        CalculateBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBMIActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 255, 0));
        Exit.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 0, 0));
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(51, 51, 255)));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(255, 255, 0));
        Clear.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 0, 0));
        Clear.setText("Clear");
        Clear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(51, 51, 255)));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        YourBMI.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        YourBMI.setForeground(new java.awt.Color(0, 0, 255));
        YourBMI.setText("Your BMI : ");

        BMI.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        BMI.setForeground(new java.awt.Color(255, 0, 0));
        BMI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BMI.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        FeetText.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        FeetText.setForeground(new java.awt.Color(255, 0, 0));
        FeetText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        comment.setBackground(new java.awt.Color(255, 255, 51));
        comment.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        comment.setForeground(new java.awt.Color(255, 0, 0));
        comment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        InchesText.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        InchesText.setForeground(new java.awt.Color(255, 0, 0));
        InchesText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(YourBMI))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(YourHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Yourweight)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalculateBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FeetText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(InchesText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Feet)
                                .addGap(66, 66, 66)
                                .addComponent(Inches)))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InchesText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeetText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YourHeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Feet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Inches))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yourweight))
                .addGap(18, 18, 18)
                .addComponent(CalculateBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YourBMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        FeetText.setText("");
        InchesText.setText("");
        WeightText.setText("");
        BMI.setText("");
        comment.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void CalculateBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBMIActionPerformed
        double feet,inches,kg,height,bmi;

        try{
            feet = Double.parseDouble(FeetText.getText());
            inches = Double.parseDouble(InchesText.getText());
            kg = Double.parseDouble(WeightText.getText());
            height = (feet * 12 ) + inches;
            height = (height * 2.5 ) / 100;
            bmi = kg/(height * height);
            BMI.setText(new DecimalFormat("##.##").format(bmi));
            if(bmi < 18.5){
                comment.setText("You are under weight.");
            }
            else if (bmi >= 18.5 && bmi <= 24.9){
                comment.setText("Your weight is normal.");
            }
            else if( bmi >= 24.9 && bmi <= 29.9){
                comment.setText("You are over weight.");
            }
            else{
                comment.setText("You are Fit.");
            }
        }
        catch(Exception e){
            comment.setText("Please check required field.");
        }
    }//GEN-LAST:event_CalculateBMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BMI;
    private javax.swing.JButton CalculateBMI;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Feet;
    private javax.swing.JTextField FeetText;
    private javax.swing.JLabel Inches;
    private javax.swing.JTextField InchesText;
    private javax.swing.JTextField WeightText;
    private javax.swing.JLabel YourBMI;
    private javax.swing.JLabel YourHeight;
    private javax.swing.JLabel Yourweight;
    private javax.swing.JLabel comment;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
